# Generated by Django 5.2.3 on 2025-06-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', '学生/冒险者'), ('teacher', '老师'), ('admin', '系统管理员')], default='student', max_length=20),
        ),
    ]
