# Generated by Django 5.2.3 on 2025-06-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='identifier',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True),
        ),
    ]
