# Generated by Django 5.2.3 on 2025-08-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='volunteerTime',
            field=models.FloatField(default=0),
        ),
    ]
