# Generated by Django 5.2.3 on 2025-08-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_volunteertime'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credit_score',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
