# Generated by Django 5.2.3 on 2025-09-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_credit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='realname',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
