# Generated by Django 5.2.3 on 2025-07-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_cancel_requested_task_invited_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
