# Generated by Django 5.2.3 on 2025-07-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_cancelled',
        ),
    ]
