# Generated by Django 5.2.3 on 2025-08-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='credit_score',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
