# Generated by Django 5.2.3 on 2025-08-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_credit_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='credit_score',
        ),
    ]
