# Generated by Django 5.2.3 on 2025-08-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_task_credit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='volunteerTime_reward',
            field=models.FloatField(default=0),
        ),
    ]
