# Generated by Django 5.2.3 on 2025-08-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_volunteertime_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='required_level',
            field=models.CharField(choices=[('F', 'F'), ('E', 'E'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S'), ('SSS', 'SSS')], default='F', max_length=10),
        ),
    ]
