# Generated by Django 5.2.3 on 2025-08-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_required_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='maximum_users',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
