# Generated by Django 5.2.3 on 2025-08-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_related_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('invite', '组队邀请'), ('system', '系统公告'), ('level_up', '等级提升'), ('task_update', '任务状态变更'), ('cancel_request', '取消任务请求'), ('completed', '任务已完成'), ('completion_request', '确认完成任务请求')], max_length=20),
        ),
    ]
